### PR TITLE
feat: use a generic key

### PR DESCRIPTION
**Pull request by TennyZhuang**
A draft PR here to show the break change.

Generally, the PR make `work` stronger, and removed `work_with_owned_key`, which is useless after we introduced a generics K.

Some type inferences are broken, but migration is not very hard.

We require `K: Hash + Eq + Clone`. In fact, as suggested by @ihciah, we can use `K: Hash + Eq + ToOwned`, and store `K::Owned` in the mapping, but I can't find the benefits while introducing a little complexity. Can you give some examples? Or we can just keep `Clone` here.

### CODE REVIEW

**Comment by TennyZhuang** [comment]
🤔 Oh I got it, if we use an owned key now, an extra clone will be applied, which is unnecessary.

Let me think if there's a better way to express it.

**Comment by ihciah** [comment]
I think this impl is good!

> I can't find the benefits while introducing a little complexity. Can you give some examples? Or we can just keep Clone here.

For example when user want to use string as the key. The `SingleFlight` instance's K usually can be `&'static str` or `String`, to allow users use runtime value as the key, he may choose `String` as `K`.

Then, for the first time it is used, the ownership of String is passed in and stored into the map, also cloned into Waiter and moved to async clouser. It's fine. But for the second time it is used, this key's lifetime can be short than the Future ready. So we can only get the reference. If accept the key as `K`(instead of `&K`), user must clone it(it will be dropped after the future dropped).

**Comment by TennyZhuang** [comment]
I got your idea, in fact you need something like this, https://docs.rs/maybe-owned-trait/latest/maybe_owned_trait/trait.MaybeOwned.html.

However introducing it may bring unnecessary complexity for callers, a easy solution is using two different methods. Let me add `work_with_owned_key` back.

**Comment by TennyZhuang** [comment]
This requirement is very similar to `HashMap::entry`. Many people have complained about why it accepts an Owned Key, but if its API were changed to accept a `&K` while `K: Clone`, it would still be complained by another group of people.

**Comment by ihciah** [comment]
> This requirement is very similar to `HashMap::entry`. Many people have complained about why it accepts an Owned Key, but if its API were changed to accept a `&K` while `K: Clone`, it would still be complained by another group of people.

Yes! So I always manually get and insert, but this will have to hash and lookup twice.



> I got your idea, in fact you need something like this, https://docs.rs/maybe-owned-trait/latest/maybe_owned_trait/trait.MaybeOwned.html.
> 
> However introducing it may bring unnecessary complexity for callers, a easy solution is using two different methods. Let me add `work_with_owned_key` back.

Merging into one seems more elegant? This crate meets the need except it can only provide blanket impl for one of `&'a str` and `&'static str`. But I think maybe this problem can be solved by make a new wrapper type like `pub struct StaticStr(pub &'static str)` and impl MaybeOwned for it. Wrapper type with one function signature I think is better than expose 2 function signatures. How do you think?

**Comment by miamia0** [comment]
Are there any updates to this pull request? I'm eager to try this feature. 🥰

**Review by ihciah — APPROVED** [review]

**Comment by ihciah** [comment]
I rethought the reference optimization mentioned earlier, and it may have little effect on saving Key clone overhead.
Thank you for your contribution!

**Pull request merged**
